"""Sidecar index interface: envelopes, quarantine verdicts, audit chains,
certificates (design §2 C2, §4). DynamoDB in production, dict-backed locally."""

from __future__ import annotations

from typing import Iterable, Optional, Protocol

from ..audit import AuditEntry
from ..envelope import GovernanceEnvelope

PENDING, CLEARED, FAILED = "PENDING", "CLEARED", "FAILED"


class Verdict:
    def __init__(self, verdict: str, verdict_digest: str, l1_score: float = 0.0,
                 l2_detail: Optional[dict] = None):
        self.verdict = verdict
        self.verdict_digest = verdict_digest
        self.l1_score = l1_score
        self.l2_detail = l2_detail or {}


class SidecarIndex(Protocol):
    # envelopes
    def put_envelope(self, env: GovernanceEnvelope) -> None: ...
    def get_envelope(self, tenant_id: str, record_id: str) -> Optional[GovernanceEnvelope]: ...
    def delete_envelope(self, tenant_id: str, record_id: str) -> None: ...
    def envelopes_by_actor(self, tenant_id: str, actor_id: str) -> Iterable[tuple[str, GovernanceEnvelope]]: ...
    def expired_envelopes(self, tenant_id: str, now: float) -> Iterable[tuple[str, GovernanceEnvelope]]: ...
    def set_legal_hold(self, tenant_id: str, record_id: str, hold: bool) -> None: ...
    # quarantine verdicts (conditional on content digest, design §8.2)
    def put_verdict(self, tenant_id: str, record_id: str, verdict: Verdict) -> None: ...
    def get_verdict(self, tenant_id: str, record_id: str) -> Optional[Verdict]: ...
    def delete_verdict(self, tenant_id: str, record_id: str) -> None: ...
    # audit
    def audit_append(self, tenant_id: str, op: str, record_id: str = "",
                     actor_id: str = "", detail: Optional[dict] = None) -> AuditEntry: ...
    def audit_entries(self, tenant_id: str) -> list[AuditEntry]: ...
    def chain_head(self, tenant_id: str) -> str: ...
    # certificates
    def put_certificate(self, tenant_id: str, cert: dict) -> None: ...
    def certificates(self, tenant_id: str) -> list[dict]: ...
